language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg dialog haveged
install:
  - pip install -e .
script:
  - pytest