name: PRs
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg dialog
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -e .
      - name: Run pytest
        run: pytest
